### PR TITLE
Named arguments

### PR DESCRIPTION
**Pull request by KillaPL**
This pull request updates all renderable classess to use named arguments. It does not update `Sprite` class, I'm not sure if it is actually ready to be used. If need be, I will update it too.

In the spirit of this change, I also made sure that all classess are initialized properly without any arguments (except Text, which has to have default font PR merged for this).

Also in spirit of this change, I removed attributes in constructor wherever they matched the default and it made things more clear. It is very nicely visible in tests for Quad and Triangle, where I was able to remove all position attributes, since only color was tested.

I noticed that default attributes for Quad were actually drawing a triangle instead of a quad, and I fixed that as well.

### CODE REVIEW

**Comment by blacktm** [comment]
This looks great! Just one failing test:

```
  1) Ruby2D::Text#width is known after updating
     Failure/Error: expect(t.width).to eq(214)
     
       expected: 214
            got: 212
     
       (compared using ==)
     # ./test/text_spec.rb:28:in `block (3 levels) in <top (required)>'
```

This fails on macOS, but maybe you're seeing a width of 214 on Linux? Just wondering if there's a text size disparity.

**Comment by KillaPL** [comment]
Yes, I changes the test to use default font, which is 20, which changed the font sizes. And yes, the tests are actually all passing on my local machine with linux.

**Comment by blacktm** [comment]
So for some reason in the failing test above, `vera.ttf` with text "Good morning world!" has a width of 212 on macOS, but 214 on Linux? Ugh... 🙄  Wonder what we should do, specify a range instead?

**Comment by KillaPL** [comment]
Just assert that the result is a number?

**Comment by blacktm** [comment]
So, I tested this on Ubuntu and macOS, and found that test width differs by just a small percentage. The longer the test snippet, the greater that difference is. So, kind of a hack, but as long as the string provided is short, it rounds to the same integer on both platforms. I shortened it to just `"Hello!"` and it returns a width of 59 on both OSes, so maybe we should just go that route. Just added a commit with this change.

**Comment by KillaPL** [comment]
Looks like a hack, but I guess it works : D

**Comment by blacktm** [comment]
Alright, I rebased with `ruby2d/master` and updated all tests. Last call — anything else you'd like to add here before merging?

**Comment by blacktm** [comment]
I can't think of anything else here, so I'll go ahead and merge to stay on the release schedule.

**Pull request merged**
