### PR TITLE
Coordinates and Collision

### PR DESCRIPTION
**Pull request by Baconthorpe**
Here's my attempt at a coordinate and collision system for ruby2d!

When I first checked out this project, one of the first things that occurred to me is that it would be helpful to have built-in tools for handling game space and the objects therein. This PR starts on delivering that, providing classes that can be used to define a physical space (Board), things in that space (Piece) and the mechanics by which these things run into each other (Collider, CollisionLayer).

This code isn't necessarily sharpened to a point, but I thought I'd show it now so I can get a sense of whether or not I'm headed in the right direction. I tried to strike a balance between simple (easy to read, solving the most obvious problems of game dev) and versatile (ready to be extended, ready for a variety of game designs), plus an occasional edit in favor of performance (not all colliders check for collision with all other colliders).

Feel free to provide feedback on the goal of this PR, the design of the code, the style and the performance.

P.S. - Thanks for making such an interesting project!

### CODE REVIEW

**Comment by Baconthorpe** [comment]
Not sure why one of the checks failed. This thing's almost entirely additions. Anyway, also open to suggestions on fixing that.

**Comment by blacktm** [comment]
Hi @Baconthorpe, thanks for the suggestion! I don't know much about collision systems, but looks really interesting — hopefully other contributors with more experience can chime in with feedback. Regarding the Windows CI failing, that should be fixed now (outdated dependencies).

**Comment by blacktm** [comment]
Here's a relevant article by @shawn42 about [collision detection in Ruby](https://spin.atomicobject.com/2012/01/30/2d-axis-aligned-bounding-box-trees/) (source code [in Gamebox](https://github.com/shawn42/gamebox/blob/master/lib/gamebox/core/aabb_tree.rb)).

**Comment by blacktm** [comment]
I think we're going to forgo a collision detection system in Ruby 2D directly and opt for the `contains?` methods instead, but this could definitely be added via its own gem.

**Pull request closed without merging**
