### PR TITLE
Implement Color#opacity=

### PR DESCRIPTION
**Pull request by KillaPL**
In the game I'm working on I have a couple of places in which I have a shape on map, that is expected to stay, and only change opacity in time. Those are things like mask that covers map when it's night, or visual effects of a fireplace (yellow rectangle that changes opacity over time to reflects light flickering).

In those places I currently have to update completely new color every time, which forces me to write some boilerplate code. It's also suboptimal, by allocating array of numbers as color with each change.

With this pull request I would like to suggest an implementation of `Color#opacity=` method, that allows updating the opacity of existing color.

Since rectangles, squares, quads and triangles are allowed to have different color per vertex, I added Color::Set class to be a wrapper over an array of colors, with #opacity= method to update each color in array.

I also made sure that implementation looks the same for each object that exposes #color getter, and that it works for each of those objects (color.rb test) in mri, native and in browser, on linux 16.04 at least.

I am fairly certain that those changes introduce no change in external api of those classes.

Please treat this PR as a suggestion, and a start of a discussion for existance of such method: I have no expectation for this to be merged if you don't wish such feature or like this implementation.

### CODE REVIEW

**Comment by blacktm** [comment]
Awesome, this is a great idea! I'll give it a spin over the next day or so, add some comments, but looks like a smart implementation at first glance. Thanks for the PR.

**Comment by KillaPL** [comment]
One bonus we get from that case that I noticed is that, given such benchmark:

```
require "ruby2d"
require "benchmark/ips"

triangle = Triangle.new(
  320,  50,
  540, 430,
  100, 430
)

Benchmark.ips do |x|
  x.report("set color") do
    triangle.color = "white"
  end

  x.report("set opacity") do
    triangle.color.opacity = 1
  end

  x.compare!
end
```

We get such results:

Warming up --------------------------------------
           set color    14.375k i/100ms
         set opacity   283.974k i/100ms
Calculating -------------------------------------
           set color    163.658k (± 1.6%) i/s -    819.375k in   5.007958s
         set opacity      8.056M (± 1.5%) i/s -     40.324M in   5.006965s

Comparison:
         set opacity:  8055760.3 i/s
           set color:   163658.2 i/s - 49.22x  slower
```

Changing only opacity instead of setting new color is almost 50 times more performant!

**Comment by blacktm** [comment]
This is great, pretty ingenious implementation. And yay performance!

Is there a way we can keep [these error messages](https://github.com/ruby2d/ruby2d/pull/26/files#diff-12f639060fdb48a490fd85cba608645dL53) for shapes when the incorrect number of colors are given? Right now, if you give, say, a quad a three-element array, users will get a friendly message. Now they get for example:

```
...application.rb:44:in `show': no implicit conversion to float from nil (TypeError)
```

And actually, I see a bug in that old implementation — should be when the provided color array length _does not_ equal the number of vertexes (not just less than).

**Comment by KillaPL** [comment]
Ah, my bad, I did actually remove the old error messages by mistake. I am sure there is a good way of having them, I will update the PR accordingly and let you know when it's done.

**Comment by KillaPL** [comment]
@blacktm I added checks for amount of colors for triangles and quads, like it was in previous implementation. I changed them however to ArgumentError, it seems more fitting and more precise.

I also added rspec tests to cover basic color behavior for triangles and quads, because having tests is awesome : )

**Comment by blacktm** [comment]
Good call on the `ArgumentError`. And those spec tests 😍

I was thinking, like on #25 in the spirit of verifying rendering in the test card (and having less things to run and visually check), should we take just one of those opacity-pulsing rectangles (or quad, or whatever), move it to the test card, and delete `color.rb`? I feel like the interface pretty well covered now with the spec tests, and so one rendering example in the test card should do it.

**Comment by KillaPL** [comment]
@blacktm I removed `color.rb` and mobed the blinking square to testcard. Would you like me to squash the commits here too? And if so, should I squash all of them into one or keep your commits separate?

**Comment by blacktm** [comment]
Cool, I think this is ready to squash (one commit is good, no need to keep mine) and merge.

**Comment by KillaPL** [comment]
@blacktm Done. There is this merge branch which doesn't appear in my `git rebase -i HEAD~2`, not sure what's going on here.

**Comment by blacktm** [comment]
Lord almighty. Was blocked from merging this thing until a `git rebase ruby2d/master` and resolving conflicts. They joys of version control 🙄 Looks clean now, tests pass, and ready to merge, whew!

**Pull request merged**
