### PR TITLE
Renderable contains

### PR DESCRIPTION
**Pull request by KillaPL**
In this PR I added a `contains?` method for all renderable classess. For each class, this method returns true or false, based on if that point is inside the area described by that instance of that class.

For cases where the logic is nontrivial (quad, triangle, line) I added a comments describing where did the math come from. I tried to make the code rather self explanatory, so we might remove those comments if we don't want them. We might introduce private `Line#distance_to(x, y)`, and everything should be fine.

Also, I didn't add it, but maybe it would be a good idea to add a testcard-like test, with all renderable classes present, and `contains?` checked for them? For example, if object contains the point, it is red, else it is blue? This should make it visually obvious, that the code work nicely.

Other than those things, it is pretty much done.

### CODE REVIEW

**Comment by blacktm** [comment]
Nice work! I wanted to see what it looked like, so I added a visual test like you alluded to — run it with `rake test:mri contains` for example. Looks good to merge if you're happy with this.

**Comment by KillaPL** [comment]
Fire away! :gun:

**Comment by blacktm** [comment]
Awesome, and thanks for figuring out the math on this.

**Comment by KillaPL** [comment]
I'm glad I could help!: )

**Pull request merged**
