### PR TITLE
introduce Ruby2D::Renderable

### PR DESCRIPTION
**Pull request by KillaPL**
Please treat this PR as a question, not a suggestion. What do you think about:
  - Introducing Renderable module to reuse #add and #remove logic, which is common across all renderable objects ?
  - introducing #rerender method to all renderable objects?

First just seems like a clean approach, second I am doing all the time, and it simply seems like something that should be native.

### CODE REVIEW

**Comment by blacktm** [comment]
You're reading my mind here, freaky. I think there will be a number of things visual objects have in common — `add` and `remove` is a great place to start.

Regarding `rerender`, there might be a misunderstanding about what's actually going on under the hood (I know the lack of documentation doesn't help). The `Application.add` and `Application.remove` methods eventually call [`add`](https://github.com/ruby2d/ruby2d/blob/v0.3.0/lib/ruby2d/window.rb#L70) and [`remove`](https://github.com/ruby2d/ruby2d/blob/v0.3.0/lib/ruby2d/window.rb#L81) in the Window class, and these methods just add and remove visual objects in the window's [`@objects` array](https://github.com/ruby2d/ruby2d/blob/v0.3.0/lib/ruby2d/window.rb#L24). On each loop (or frame), the frame buffer is cleared via OpenGL, the `render()` function is called in the extensions, the `@objects` array [is read and iterated on](https://github.com/ruby2d/ruby2d/blob/v0.3.0/ext/ruby2d/ruby2d.c#L499), and each element is redrawn in the empty window (and repeat 60 times per second).

So in the case of `rerender` calling `add` and `remove` (maybe you meant `remove` then `add`?), this is simply removing the renderable object from that window array, with a `@objects.delete_at(i)`, and adding it back with `@objects.push(o)`, so the effect is that it just alters the rendering order on each `render()` frame, not actually re-rendering or something. _However_, that behavior is useful, so maybe we introduce some rendering order methods, like `obj.send_to :front` or `obj.send_to :back`, or something. That way, people can create (with `.new`) renderable objects in whatever order they want, but then have some control over what order they get rendered. Does that make sense?

**Comment by KillaPL** [comment]
I removed the #rerender method, I'll be glad to continue the discussion, here or in separate issue.

I am aware what is the behavior of #add and #remove, however the effect in the end is, as you mentioned, that the object that was removed and added, is now on top of other objects, which is what I want. For example, in my game I have a concept of designating a zone. Graphically, for now, I just render a white square, but if there was any other object in that place, it must be on top of the zone square, see this image:

zones_rendering

In area pointed by arrow you can see a lone tree (a lot of those in screen), and a zone designated white area. There is bigger 5x5 area too. Then there is zone under the tree. What happens is, on click i save the data about zone, render the white square, and then remove and add the tree, so that it is on top of the square. This is what I need, so `.send_to(:front)` and `send_to(:back)` would probably work well for me, and probably improve performance too : )

**Comment by blacktm** [comment]
Got it, that's helpful, thanks. And the game is looking really good! How would you feel about merging this as is, with `add` and `remove` to start, then creating a new issue to discuss object ordering, design the API? I think we could come up with other useful methods like `.swap(obj1, obj2)`, `.above(obj)`, `.below(obj)`, prioritizing on our real-world needs to start.

**Comment by KillaPL** [comment]
> And the game is looking really good!

Thank you, and I hope that's just the beginning!

As far as I'm aware there is nothing to add here and it's squashed, so you can merge. I will create new issue for new APIs.

**Comment by blacktm** [comment]
Sounds good, ship it 🚢

**Pull request merged**
