### PR TITLE
Add mouse events

### PR DESCRIPTION
**Pull request by blacktm**

### CODE REVIEW

**Comment by KillaPL** [comment]
@blacktm Works spectacularily! 
clapping

**Comment by blacktm** [comment]
@KillaPL I think this is good to go if you want to give it a 👀 over. Make sure to run `git submodule update --remote` since the submodule was updated.

**Comment by KillaPL** [comment]
Looks good. Seems I have my entire gui controls to rewrite : D

**Comment by blacktm** [comment]
Ha, yes, downside is that you might have to do some rewriting. Regarding 1) Yes, I was anticipating this would be in a v0.4.0 release, along with all other [changes since v0.3.0](https://github.com/ruby2d/ruby2d/compare/v0.3.0...master) (I don't have a preference of when to cut a new release, although would be nice to get a few issues fixed, like `File.exists?`). 2) Yea, I think we can do event adding/removing in another PR, since there's a lot already going on in this one. I'm still fuzzy on what the DSL would look like, so we could either open a new issue to sketch it out, or if you want to go right to a PR, that's fine too.

**Comment by KillaPL** [comment]
> Ha, yes, downside is that you might have to do some rewriting.

By no means I meant that as a bad thing, check my edit comments, this cleans up and simplifies a lot of my code!

> I don't have a preference of when to cut a new release

I personally always use master and compile the code locally, so I am not pushing. I asked about that purely from curiosity.

I'll try doing a PR with events unbinding, I believe this can be done in pure ruby.

**Comment by KillaPL** [comment]
Check this: https://drive.google.com/file/d/0B3t54jmgjfm7VVI3NkxLbmRUTWM/view

As far as I'm aware, it's all nice and peachy, finally I can set things by area instead of clicking one by one

my_job_here_is_done

**Comment by blacktm** [comment]
Awesome, glad you've found this so beneficial. I really like where we ended up on input events broadly, much more clear. Thanks for all your feedback along the way. I'll go ahead and merge this.

And the game looks great! So fun to see it progress.

**Pull request merged**
