### PR TITLE
introduce lines

### PR DESCRIPTION
**Pull request by KillaPL**
And now for me new trick: A Line class : )

### CODE REVIEW

**Comment by blacktm** [comment]
Given that a line is quite fundamental (and not so trivial to implement), I'm thinking it might make more sense after all to add a `S2D_DrawLine` in the Simple 2D project, and make the Ruby `Line` class simply an interface for it. That ok? I can open a PR to the C and JS versions to add the function.

**Comment by KillaPL** [comment]
Sure, why not. If you feel that is a good idea, let's go that way.

**Comment by blacktm** [comment]
Ok, I've got PRs to add lines in Simple 2D (in [C](https://github.com/simple2d/simple2d/pull/53) and [JS](https://github.com/simple2d/simple2d.js/pull/4)) and pushed a commit here that would take advantage of the new `DrawLine` functions.

**Comment by KillaPL** [comment]
That is certainly fine by me, as long as it works: ]

**Comment by blacktm** [comment]
Done, hooray! Thanks so much for figuring out the math on this (gave you credit in https://github.com/simple2d/simple2d/commit/ab53c87a44abc09f269669d1bf251f127b956847 and https://github.com/simple2d/simple2d.js/commit/e64479e95baf890e1f216842c0bcc631f65bfb27 also).

**Comment by KillaPL** [comment]
Always happy to help with the maths, that is my strong suit. I studied it for almost 4 years; ).

I'm happy to see it merged! Well done!

**Pull request merged**
