### PR TITLE
added very simple build support for *BSD

### PR DESCRIPTION
**Pull request by compufox**
Simple2D just merged a PR to add build support for BSD systems, so I thought I'd send this PR to complete the package!

### CODE REVIEW

**Comment by blacktm** [comment]
Hi @theZacAttacks. Thanks for the PR! The `extconf.rb` has since changed, so I made some updates. Would you be able to give this a try, see if everything works ok? I had to force push to resolved merge conflicts, so you may want to get a fresh pull of the branch, update the submodules with `rake update`, then run `rake` to build and install the gem.

**Review by blacktm — APPROVED** [review]

**Comment by hkwadam** [comment]
So there is a bit of a difference between BSD package managers.

FreeBSD uses pkgng
NetBSD uses pkgsrc
OpenBSD uses their own packaging system which is literally shell scripts
etc... so the simple determination of BSD in the uname, and using pkg (FreeBSD's option) won't suffice overall. I can help with Free- (should be more or less taken care of with the changes in this PR) and OpenBSD, but have little experience with NetBSD.

**Comment by desnudopenguino** [comment]
Took a look at this MR from a discussion in discord. It's a good start, but only takes into account one package manager for one BSD (FreeBSD).

To work automagically, it would need to determine the specific BSD via uname, then use the proper package manager and sudo-esque tool. For example, OpenBSD uses their own package manager which is a set of shell scripts, and has a native tool called doas instead of sudo. I can help with the OpenBSD part, because that's where a majority of my time is spent.

Another thing to note is that the BSD's aren't like linux. Each BSD is a completely separate OS built on a separate kernel, and with a separate set of userland tools. What works for one should be able to be translated for the next, but they may not have the exact same implementation of some things.

**Comment by blacktm** [comment]
Thanks for the background @desnudopenguino! Would love help to improve BSD support.

**Pull request merged**
