### PR TITLE
Implements volume control to Music objects

### PR DESCRIPTION
**Pull request by heitorado**
This PR contributes to #115 

Since Simple2D does not have an implementation of the volume control offered in SDL, the native SDL function was used, as suggested by @amicloud.

- The method 'volume' can be called from any ```Music``` object. 
- If no parameters passed, the method returns the current volume of the music. 
- If a number 0-100 is provided, the music volume is adjusted in that percentage. 
- Bigger values will always result in 100% volume and less than 0 values will have the same behavior as not providing any arguments.

### CODE REVIEW

**Comment by blacktm** [comment]
Looks great, nice job! One thing to mention, SDL isn't actually used in the web extension, just the [native browser APIs](https://developer.mozilla.org/en-US/docs/Web/API/HTMLAudioElement#Methods) (we made a port of Simple 2D [in JavaScript here](https://github.com/simple2d/simple2d.js)). But, in bigger news, we're going to be re-implementing "building for the web" using WebAssembly (see #93) which will use the SDL APIs just like we would natively. So in short, we could actually drop those changes from `ruby2d-opal.rb`. A bunch of stuff is broken on the web now, so we might just disable web building until WebAssembly is done.

**Comment by blacktm** [comment]
Yep, you got it. The `ruby2d-opal.rb` file will be removed entirely in the near future.

**Comment by heitorado** [comment]
It's a good idea! I'm trying to implement it with the other changes I'm making but without success. What else needs to be done to define a class method? (I did ```def self.volume``` and called ```ext_volume```)

**Comment by blacktm** [comment]
Yes, `self.volume` should work. If you want to add that to the PR and remove the changes to `ruby2d-opal.rb`, I think this is good to merge. We can work on Sound volume in a new PR, or discuss in #115.

**Comment by heitorado** [comment]
I've removed the changes from ```ruby2d-opal.rb``` and commited.

```self.volume``` is not working though. I've defined it like this:

`def self.volume(percentage = -1)
      (ext_volume(percentage)/128.0)*100
end`

And upon calling ```Music.volume``` it throws the following error:
```1: from color-dodge.rb:104:in `block in <main>'
/home/heitorado/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ruby2d-0.6.0/lib/ruby2d/music.rb:48:in `volume': undefined method `ext_volume' for Ruby2D::Music:Class (NoMethodError)
Did you mean?  volume```

**Comment by blacktm** [comment]
Ah, we need to define a class method. Just added a commit to define `r_define_class_method()`.

Also, I think in the `ext_volume` C method, we should use `MIX_MAX_VOLUME` as the [docs suggest](https://www.libsdl.org/projects/SDL_mixer/docs/SDL_mixer_61.html). While it's defined [in the source](https://hg.libsdl.org/SDL/file/18f3294b230e/include/SDL_audio.h#l616) as `128`, that could change. Maybe we can do this instead:

```c
return INT2FIX(
  Mix_VolumeMusic(MIX_MAX_VOLUME * (vol / 100.0))
);
```

And the `volume` method just becomes:

```ruby
def volume(percentage = -1)
  ext_volume(percentage)
end
```

That make sense?

**Comment by blacktm** [comment]
Oops, forgot to take into account `-1`, so maybe it would be instead:

```c
mix_vol = vol == -1 ? -1 : MIX_MAX_VOLUME * (vol / 100.0);

return INT2FIX(
  Mix_VolumeMusic(mix_vol)
);
```

I'm looking to cut a new release ASAP to fix some bugs, so if this looks good, would love to get it in there.

**Comment by heitorado** [comment]
Yes, that looks better! I've made those changes on my last commit. Tested it and all is working!

I just added one more thing, to return the volume as a percentage (since its passed as one), not in the range from 0 - 128.

I ignored the -1 case before, because I thought that less than zero values would have the same effect as -1. I haven't found anything about it on the docs, so your approach is better.

I'm with one last problem in this PR - When I call ```Music.volume``` (without any parameters) it throws the following error:

```
1: from /home/heitorado/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ruby2d-0.6.0/lib/ruby2d/window.rb:358:in `update_callback'
color-dodge.rb:106:in `block in <main>': undefined method `volume' for #<Ruby2D::Music:0x000055a17b2ad178> (NoMethodError)
Did you mean?  ext_volume
```

After that is fixed, I think we're good to go!

**Comment by blacktm** [comment]
Good catch on the percentage being returned. In the process of fixing `Music.volume`, I rethought a few things. When we're just assigning values, we use the standard attribute reading/writing approach elsewhere (e.g. square.x = 100). Maybe we can do that here too, like `Music.volume` and `Music.volume = 50` for example. I pushed a commit that only creates a `ext_volume` class method, and the instance methods are now aliased to `Music.volume/=` which uses it. Also, I adjusted the API a bit so values less than 0 (like negative numbers) just set the volume to 0. Now we only have to call `ext_volume(-1)` on `Music.volume`. While testing, I also discovered that my `FIX2INT()` MRuby macro is totally wrong, d'oh! I changed them to `NUM2INT()` which now works (I'll remove all the Fixnum macros in a different PR). Finally, I added some RSpec tests and a volume bar to the `audio.rb` test, which you can try by running:

```bash
rake && rake test:int audio
```

(Click the green bar to change the volume.) I can't seem to find any other issues, so if you're happy with it, I think it's good to merge, whew!

**Comment by heitorado** [comment]
Hey, that's cool! Nice changes on creating only the class method and using the assignment operator. Everything looks much cleaner now.

Just one last little thing that I noticed, when you set the volume like ```Music.volume = x``` It always returns x. This is okay for >= 0 values, but since less than zero values are meant to put the volume at 0%, I think it should return 0. I've read and tested this for couple hours but I can't find why the Mix_VolumeMusic at ruby2d.c is returning the negative value, since it's passed from the ruby method as zero.
I wonder if assignments in ruby default to always return the value that was assgined?


And just for making sure that I got the "rules" about the volume implementation on the gem:
- Passing values that are less than zero is the same as passing zero.
- Passing values that are more than 100 is the same as passing 100.
- Passing no values means you just want to get the current volume (0-100).

Is that it?

**Comment by blacktm** [comment]
Yea, it looks like the assignment operator always returns the value being assigned. I tried to override it, but Ruby won't let me. I read a bit about it, and it's a language feature so people can have predictable return values, like for chained assignment: `a = b = c = 10`. The weird thing is that the `=` is part of the method name, `volume=(v)`, but Ruby doesn't care and still treats it like an operator.

And yes, that's what I was thinking about for the "rules." We could throw errors for values less and more than 0..100, but we've found a benefit for being tolerant, say if the values are calculated by some formula and happen to be out of range.

**Comment by heitorado** [comment]
Huh, that's weird. But since it's a language restriction I guess it's ok.

I also like the tolerancy (not throwing errors). I was thinking the same, out of range values can be quite common if changing volume dinamically during the game.

Since the = operator can't have an override, I think we're good to merge!

**Comment by blacktm** [comment]
Left for some travel before getting a chance to merge this. Thanks again for the contribution @heitorado!

**Pull request merged**
