### PR TITLE
dispatch rendering to rendered classess

### PR DESCRIPTION
**Pull request by KillaPL**
Continuing our conversation about removing `type_id` as unnecessary from ruby code, an idea came to me: Why do we assign values to classess, and then call specific logic based on those assigned values, if we can be good object-oriented programmers, and simply dispatch expected logic to those classess. So With a little bit experimentation I did that for js extension (since I can handle js, unlike c). This actually works very well, and I would say it simplifies the code. To make the story short:

* Defines `ext_render` method for all renderable classess
* Removes the need for `@type_id` instance variable
* Inside render loop, simply calls `ext_render` on each object.

Additionally, I might say, this makes the code easier to understand, which in the long run might pave the way for implementation of more complex features, or for performance improvements. I am already wondering if some of those render methods might be organised in more efficient manner; )

@blacktm  what do you think?

### CODE REVIEW

**Comment by KillaPL** [comment]
@blacktm Ok, I finished this, also with c code. I reorganised the render loop in such way that it will simply call "render_ext" method on each object in the rendered array. This makes the rendering behavior local to rendered class. For now the main point is that it allowed removal of `@type_id` variables form the ruby code, but it also opens the possibility to benchmark, profile, and optimise rendering time for renderable methods, since we can just measure how long it takes to do `Square#ext_render` and others. 

Of course, and as always, this is only an idea. Let me know what you think : )

**Comment by KillaPL** [comment]
I'm not sure why this says there are conflicts. As far as my git abilities tell me, this should be fine. Could have done something wrong: (

**Comment by blacktm** [comment]
Just a heads up, I'm rebasing and resolving conflicts now, a few more spot checks and should be good to go. Sorry for the delay!

**Comment by blacktm** [comment]
I think this is now good to merge. Only things I changed were updating the `ext_` method names for consistency (no need to have the class name in them) and in Opal putting new lines around multi-line JavaScript snippets (I also encountered the mandatory new line issue with Opal's parser).

**Comment by KillaPL** [comment]
I'm good with the classess changing. There is nothing more to add from me for certain : )

**Comment by blacktm** [comment]
Awesome, merged!

**Pull request merged**
